title: "gbljdgb's blog" # 网页标题栏（在最上面悬浮的那个）
description: "maybe i wanna share something..." # 在网站标题下显示
name: "gbljdgb's blog" # 网站标题
avater: https://gbljdgb.github.io/images/avatar.png
favicon: https://gbljdgb.github.io/images/favicon.ico

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
